<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mate</string>
	</array>
	<key>name</key>
	<string>Mate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(programa)\b</string>
			<key>name</key>
			<string>keyword.meta.namespace.mate</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(funcion)\b</string>
			<key>name</key>
			<string>keyword.meta.function.mate</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(si|pero|no|regresa|mientras)\b</string>
			<key>name</key>
			<string>keyword.control.mate</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mate</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.mate</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.mate</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mate</string>
		</dict>
	</array>
	<key>scope</key>
	<string>source.mate</string>
	<key>scopeName</key>
	<string>source.mate</string>
	<key>uuid</key>
	<string>95244055-721F-4717-B900-FCED0A3D5405</string>
</dict>
</plist>
